/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fjuul.engagement.sdk.analytics;

import org.junit.Test;
import static org.junit.Assert.*;

public class AnalyticsTest {
    @Test public void testSomeLibraryMethod() {
        Analytics classUnderTest = new Analytics();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testGetTextMethod() {
        Analytics classUnderTest = new Analytics();
        assertEquals("Hello, Core", classUnderTest.getText());
    }
}
