/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fjuul.engagement.sdk;

public class FjuulSDK {
    public boolean someLibraryMethod() {
        return true;
    }
}
