trailing_comma:
    mandatory_comma: true
line_length:
  warning: 180
  error: 200
disabled_rules:
  - multiple_closures_with_trailing_closure
  - identifier_name
excluded:
  - "**/*.generated.swift"
