/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fjuul.engagement.sdk.analytics;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
