/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fjuul.engagement.sdk;

import static org.junit.Assert.*;

import org.junit.Test;

public class FjuulSDKTest {
    @Test
    public void testSomeLibraryMethod() {
        FjuulSDK classUnderTest = new FjuulSDK();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
