name: Publish Android

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish package
        working-directory: ./android
        run: ./gradlew publish -PVERSION_NAME=${GITHUB_REF#refs/tags/v}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
