name: Test Android

on:
  pull_request:
    paths:
      - android/**
      - .github/workflows/**

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: lint
      working-directory: ./android
      run: ./gradlew spotlessCheck
    - name: android-lint
      working-directory: ./android
      run: ./gradlew lint
    - name: unit tests
      timeout-minutes: 5
      working-directory: ./android
      run: ./gradlew clean testRelease
    - name: build fjuul-sdk for the local maven repo
      working-directory: ./android
      run: ./gradlew publishFjuulSDKPublicationToMavenLocal -PVERSION_NAME=100.0.0-SNAPSHOT
    - name: enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: ui tests (example app)
      timeout-minutes: 15
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 26
        working-directory: ./android/ExampleApp
        script: ./gradlew app:connectedAndroidTest
