name: Test iOS

on:
  pull_request:
    paths:
      - Package.swift
      - Package.resolved
      - ios/**
      - .github/workflows/**

jobs:

  test:

    runs-on: macOS-15-large

    steps:
    - uses: actions/checkout@v5
    - run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: lint
      run: |
        (cd ios; swiftlint)
    - name: xcode test Fjuul SDK-Package
      run: |
        set -o pipefail && xcodebuild \
          -scheme "Fjuul SDK-Package" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
          test | xcpretty
    - name: xcode test ExampleApp
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme ExampleApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
          test | xcpretty
