name: Test iOS

on:
  push:
    paths:
      - ios/**
      - .github/workflows/**

jobs:

  test:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Test Core
      run: |
        cd ios/Core
        swift test
    - name: Test Analytics
      run: |
        cd ios/Analytics
        swift test
