name: Test Android

on:
  push:
    paths:
      - android/**
      - .github/workflows/**

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check code style
      working-directory: ./android
      run: ./gradlew spotlessCheck

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Tests
      working-directory: ./android
      run: ./gradlew clean test
