name: Test iOS

on:
  pull_request:
    paths:
      - ios/**
      - .github/workflows/**

jobs:

  test:

    runs-on: macOS-10.15

    steps:
    - uses: actions/checkout@v2
    # - run: swift test
    - name: lint
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
        (cd ios; swiftlint)
    - name: xcode test FjuulCore
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme FjuulCore \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.6' \
          test | xcpretty
    - name: xcode test FjuulCore
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme FjuulCore \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.6' \
          test | xcpretty
    - name: xcode test FjuulAnalytics
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme FjuulAnalytics \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.6' \
          test | xcpretty
    - name: xcode test FjuulUser
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme FjuulUser \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.6' \
          test | xcpretty
    - name: xcode test ExampleApp
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme ExampleApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.6' \
          test | xcpretty
