name: Test iOS

on:
  pull_request:
    paths:
      - Package.swift
      - Package.resolved
      - ios/**
      - .github/workflows/**

jobs:

  test:

    runs-on: macOS-10.15

    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: |
        (cd ios; swiftlint)
    - name: xcode test Fjuul SDK-Package
      run: |
        set -o pipefail && xcodebuild \
          -scheme "Fjuul SDK-Package" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=14.3' \
          test | xcpretty
    - name: xcode test ExampleApp
      run: |
        set -o pipefail && xcodebuild \
          -workspace ios/SDK.xcworkspace \
          -scheme ExampleApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=14.3' \
          test | xcpretty
