name: Test Android

on:
  push:
    paths:
      - android/**
      - .github/workflows/**

jobs:

  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: lint
      working-directory: ./android
      run: ./gradlew spotlessCheck
    - name: unit tests
      working-directory: ./android
      run: ./gradlew clean test
    - name switch to the example app
      working-directory: ./android/ExampleApp
    - name: set up android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        script: ./gradlew app:connectedAndroidTest
