name: Update SBOM

permissions:
  contents: write

on:
  push:
    branches:
      - master
      - chore/restrict-dep-graph

concurrency:
  group: sbom-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  update-sbom:
    name: update-sbom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Note: setup-java is required to inject a valid settings.xml consuming the GitHub credentials
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false
      - name: update Gradle SBOM
        working-directory: "android"
        run: ./gradlew assembleRelease
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: releaseRuntimeClasspath
